# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import core_pb2 as core__pb2
from . import fate_engine_service_pb2 as fate__engine__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fate_engine_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FateEngineServiceStub(object):
    """Service for interacting with the Fate Engine
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitProposal = channel.unary_unary(
                '/tsukuyomi.service.FateEngineService/SubmitProposal',
                request_serializer=core__pb2.Proposal.SerializeToString,
                response_deserializer=fate__engine__service__pb2.SubmitProposalResponse.FromString,
                _registered_method=True)
        self.GetWorldState = channel.unary_unary(
                '/tsukuyomi.service.FateEngineService/GetWorldState',
                request_serializer=fate__engine__service__pb2.GetWorldStateRequest.SerializeToString,
                response_deserializer=core__pb2.WorldState.FromString,
                _registered_method=True)
        self.StreamTickUpdates = channel.unary_stream(
                '/tsukuyomi.service.FateEngineService/StreamTickUpdates',
                request_serializer=fate__engine__service__pb2.StreamTickUpdatesRequest.SerializeToString,
                response_deserializer=core__pb2.TickState.FromString,
                _registered_method=True)
        self.RegisterActor = channel.unary_unary(
                '/tsukuyomi.service.FateEngineService/RegisterActor',
                request_serializer=fate__engine__service__pb2.RegisterActorRequest.SerializeToString,
                response_deserializer=fate__engine__service__pb2.RegisterActorResponse.FromString,
                _registered_method=True)


class FateEngineServiceServicer(object):
    """Service for interacting with the Fate Engine
    """

    def SubmitProposal(self, request, context):
        """Allows an actor to submit a proposal to the Fate Engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorldState(self, request, context):
        """Retrieves the current world state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTickUpdates(self, request, context):
        """Streams real-time tick updates (e.g., for clients or observers)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterActor(self, request, context):
        """Registers a new actor in the world state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FateEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitProposal,
                    request_deserializer=core__pb2.Proposal.FromString,
                    response_serializer=fate__engine__service__pb2.SubmitProposalResponse.SerializeToString,
            ),
            'GetWorldState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorldState,
                    request_deserializer=fate__engine__service__pb2.GetWorldStateRequest.FromString,
                    response_serializer=core__pb2.WorldState.SerializeToString,
            ),
            'StreamTickUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTickUpdates,
                    request_deserializer=fate__engine__service__pb2.StreamTickUpdatesRequest.FromString,
                    response_serializer=core__pb2.TickState.SerializeToString,
            ),
            'RegisterActor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterActor,
                    request_deserializer=fate__engine__service__pb2.RegisterActorRequest.FromString,
                    response_serializer=fate__engine__service__pb2.RegisterActorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tsukuyomi.service.FateEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tsukuyomi.service.FateEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FateEngineService(object):
    """Service for interacting with the Fate Engine
    """

    @staticmethod
    def SubmitProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsukuyomi.service.FateEngineService/SubmitProposal',
            core__pb2.Proposal.SerializeToString,
            fate__engine__service__pb2.SubmitProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorldState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsukuyomi.service.FateEngineService/GetWorldState',
            fate__engine__service__pb2.GetWorldStateRequest.SerializeToString,
            core__pb2.WorldState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTickUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tsukuyomi.service.FateEngineService/StreamTickUpdates',
            fate__engine__service__pb2.StreamTickUpdatesRequest.SerializeToString,
            core__pb2.TickState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsukuyomi.service.FateEngineService/RegisterActor',
            fate__engine__service__pb2.RegisterActorRequest.SerializeToString,
            fate__engine__service__pb2.RegisterActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
