# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fate_engine_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fate_engine_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66\x61te_engine_service.proto\x12\x11tsukuyomi.service\x1a\ncore.proto\"L\n\x14RegisterActorRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\"P\n\x15RegisterActorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rsession_token\x18\x03 \x01(\t\"P\n\x16SubmitProposalResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bproposal_id\x18\x03 \x01(\t\"\x16\n\x14GetWorldStateRequest\"\x1a\n\x18StreamTickUpdatesRequest2\x83\x03\n\x11\x46\x61teEngineService\x12U\n\x0eSubmitProposal\x12\x18.tsukuyomi.core.Proposal\x1a).tsukuyomi.service.SubmitProposalResponse\x12T\n\rGetWorldState\x12\'.tsukuyomi.service.GetWorldStateRequest\x1a\x1a.tsukuyomi.core.WorldState\x12]\n\x11StreamTickUpdates\x12+.tsukuyomi.service.StreamTickUpdatesRequest\x1a\x19.tsukuyomi.core.TickState0\x01\x12\x62\n\rRegisterActor\x12\'.tsukuyomi.service.RegisterActorRequest\x1a(.tsukuyomi.service.RegisterActorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fate_engine_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERACTORREQUEST']._serialized_start=60
  _globals['_REGISTERACTORREQUEST']._serialized_end=136
  _globals['_REGISTERACTORRESPONSE']._serialized_start=138
  _globals['_REGISTERACTORRESPONSE']._serialized_end=218
  _globals['_SUBMITPROPOSALRESPONSE']._serialized_start=220
  _globals['_SUBMITPROPOSALRESPONSE']._serialized_end=300
  _globals['_GETWORLDSTATEREQUEST']._serialized_start=302
  _globals['_GETWORLDSTATEREQUEST']._serialized_end=324
  _globals['_STREAMTICKUPDATESREQUEST']._serialized_start=326
  _globals['_STREAMTICKUPDATESREQUEST']._serialized_end=352
  _globals['_FATEENGINESERVICE']._serialized_start=355
  _globals['_FATEENGINESERVICE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
