# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . from . import core_pb2 as core__pb2
from . from . import guest_api_pb2 as guest__api__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in guest_api_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GuestServiceStub(object):
    """Standalone Guest API for external agents"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
            "/tsukuyomi.guest.GuestService/Handshake",
            request_serializer=guest__api__pb2.HandshakeRequest.SerializeToString,
            response_deserializer=guest__api__pb2.HandshakeResponse.FromString,
            _registered_method=True,
        )
        self.Pulse = channel.unary_unary(
            "/tsukuyomi.guest.GuestService/Pulse",
            request_serializer=guest__api__pb2.PulseRequest.SerializeToString,
            response_deserializer=guest__api__pb2.PulseResponse.FromString,
            _registered_method=True,
        )
        self.SubmitProposal = channel.unary_unary(
            "/tsukuyomi.guest.GuestService/SubmitProposal",
            request_serializer=core__pb2.Proposal.SerializeToString,
            response_deserializer=guest__api__pb2.SubmitProposalResponse.FromString,
            _registered_method=True,
        )
        self.Subscribe = channel.unary_stream(
            "/tsukuyomi.guest.GuestService/Subscribe",
            request_serializer=guest__api__pb2.SubscribeRequest.SerializeToString,
            response_deserializer=core__pb2.TickState.FromString,
            _registered_method=True,
        )
        self.Disconnect = channel.unary_unary(
            "/tsukuyomi.guest.GuestService/Disconnect",
            request_serializer=guest__api__pb2.DisconnectRequest.SerializeToString,
            response_deserializer=guest__api__pb2.DisconnectResponse.FromString,
            _registered_method=True,
        )


class GuestServiceServicer(object):
    """Standalone Guest API for external agents"""

    def Handshake(self, request, context):
        """Handshake protocol to establish a guest connection"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Pulse(self, request, context):
        """Pulse to maintain connection and heartbeat"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubmitProposal(self, request, context):
        """Submit a proposal to the Fate Engine"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Subscribe(self, request, context):
        """Subscribe to world updates"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Disconnect(self, request, context):
        """Gracefully leave the simulation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GuestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Handshake": grpc.unary_unary_rpc_method_handler(
            servicer.Handshake,
            request_deserializer=guest__api__pb2.HandshakeRequest.FromString,
            response_serializer=guest__api__pb2.HandshakeResponse.SerializeToString,
        ),
        "Pulse": grpc.unary_unary_rpc_method_handler(
            servicer.Pulse,
            request_deserializer=guest__api__pb2.PulseRequest.FromString,
            response_serializer=guest__api__pb2.PulseResponse.SerializeToString,
        ),
        "SubmitProposal": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitProposal,
            request_deserializer=core__pb2.Proposal.FromString,
            response_serializer=guest__api__pb2.SubmitProposalResponse.SerializeToString,
        ),
        "Subscribe": grpc.unary_stream_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=guest__api__pb2.SubscribeRequest.FromString,
            response_serializer=core__pb2.TickState.SerializeToString,
        ),
        "Disconnect": grpc.unary_unary_rpc_method_handler(
            servicer.Disconnect,
            request_deserializer=guest__api__pb2.DisconnectRequest.FromString,
            response_serializer=guest__api__pb2.DisconnectResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tsukuyomi.guest.GuestService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "tsukuyomi.guest.GuestService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class GuestService(object):
    """Standalone Guest API for external agents"""

    @staticmethod
    def Handshake(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tsukuyomi.guest.GuestService/Handshake",
            guest__api__pb2.HandshakeRequest.SerializeToString,
            guest__api__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Pulse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tsukuyomi.guest.GuestService/Pulse",
            guest__api__pb2.PulseRequest.SerializeToString,
            guest__api__pb2.PulseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitProposal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tsukuyomi.guest.GuestService/SubmitProposal",
            core__pb2.Proposal.SerializeToString,
            guest__api__pb2.SubmitProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Subscribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/tsukuyomi.guest.GuestService/Subscribe",
            guest__api__pb2.SubscribeRequest.SerializeToString,
            core__pb2.TickState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Disconnect(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tsukuyomi.guest.GuestService/Disconnect",
            guest__api__pb2.DisconnectRequest.SerializeToString,
            guest__api__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
