# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fate_engine_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fate_engine_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66\x61te_engine_service.proto\x12\x11tsukuyomi.service\x1a\ncore.proto\"P\n\x16SubmitProposalResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bproposal_id\x18\x03 \x01(\t\"\x16\n\x14GetWorldStateRequest\"\x1a\n\x18StreamTickUpdatesRequest2\x9f\x02\n\x11\x46\x61teEngineService\x12U\n\x0eSubmitProposal\x12\x18.tsukuyomi.core.Proposal\x1a).tsukuyomi.service.SubmitProposalResponse\x12T\n\rGetWorldState\x12\'.tsukuyomi.service.GetWorldStateRequest\x1a\x1a.tsukuyomi.core.WorldState\x12]\n\x11StreamTickUpdates\x12+.tsukuyomi.service.StreamTickUpdatesRequest\x1a\x19.tsukuyomi.core.TickState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fate_engine_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITPROPOSALRESPONSE']._serialized_start=60
  _globals['_SUBMITPROPOSALRESPONSE']._serialized_end=140
  _globals['_GETWORLDSTATEREQUEST']._serialized_start=142
  _globals['_GETWORLDSTATEREQUEST']._serialized_end=164
  _globals['_STREAMTICKUPDATESREQUEST']._serialized_start=166
  _globals['_STREAMTICKUPDATESREQUEST']._serialized_end=192
  _globals['_FATEENGINESERVICE']._serialized_start=195
  _globals['_FATEENGINESERVICE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
